from sqlalchemy.orm import Session
from db.models import RuleBase

SEED_RULES = [
    # --- CENTRAL LEGAL METROLOGY (PACKAGED COMMODITIES) RULES, 2011 ---
    {
        "rule_id": "PCR_RULE_1",
        "jurisdiction": "CENTRAL",
        "legal_source": "Legal Metrology (Packaged Commodities) Rules, 2011",
        "section": None,
        "rule": "1",
        "sub_rule": "1-2",
        "clause": None,
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["all_packaged_commodities", "india_territory"],
        "conditions": ["enforcement_from_1st_april_2011"],
        "requirements": ["Short title: Legal Metrology (Packaged Commodities) Rules, 2011", "Extends to whole of India"],
        "exceptions": [],
        "exemptions": [],
        "violation": [],
        "evidence_required": [],
        "penalty": [],
        "compounding": [],
        "authority": ["Department of Consumer Affairs, Government of India"],
        "source_reference": "PCR 2011, Rule 1"
    },
    {
        "rule_id": "PCR_RULE_2",
        "jurisdiction": "CENTRAL",
        "legal_source": "Legal Metrology (Packaged Commodities) Rules, 2011",
        "section": None,
        "rule": "2",
        "sub_rule": None,
        "clause": "a-z",
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["definitions", "legal_terms"],
        "conditions": [],
        "requirements": [
            "Defines key terms: consumer, manufacturer, packer, importer, retail package, wholesale package, net quantity, pre-packed commodity, e-commerce entity, unit sale price"
        ],
        "exceptions": [],
        "exemptions": [],
        "violation": [],
        "evidence_required": [],
        "penalty": [],
        "compounding": [],
        "authority": ["Department of Consumer Affairs, Government of India"],
        "source_reference": "PCR 2011, Rule 2"
    },
    {
        "rule_id": "PCR_RULE_3",
        "jurisdiction": "CENTRAL",
        "legal_source": "Legal Metrology (Packaged Commodities) Rules, 2011",
        "section": None,
        "rule": "3",
        "sub_rule": None,
        "clause": "a-c",
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["retail_packages", "industrial_consumers", "institutional_consumers"],
        "conditions": ["packages_meant_for_industrial_or_institutional_consumers"],
        "requirements": ["Chapter II retail provisions do not apply to industrial/institutional consumers or packages above 25kg/25L (except cement/fertilizers)"],
        "exceptions": ["cement_and_fertilizers_sold_in_bags_up_to_50kg"],
        "exemptions": ["industrial_consumers", "institutional_consumers"],
        "violation": ["Applying retail exemptions to retail consumer packages"],
        "evidence_required": ["Purchase invoice showing direct industrial supply"],
        "penalty": ["Section 36(1) of Legal Metrology Act, 2009"],
        "compounding": ["Compoundable under Section 48"],
        "authority": ["Director of Legal Metrology"],
        "source_reference": "PCR 2011, Rule 3"
    },
    {
        "rule_id": "PCR_RULE_4",
        "jurisdiction": "CENTRAL",
        "legal_source": "Legal Metrology (Packaged Commodities) Rules, 2011",
        "section": None,
        "rule": "4",
        "sub_rule": "1",
        "clause": None,
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["pre_packaged_commodities", "retail_traders"],
        "conditions": ["offered_for_sale"],
        "requirements": ["No person shall pre-pack, sell, distribute, deliver, or display for sale any pre-packaged commodity unless compliant with declarations"],
        "exceptions": [],
        "exemptions": [],
        "violation": ["Sale or storage of non-compliant pre-packaged commodity"],
        "evidence_required": ["Seizure memo", "Sample package"],
        "penalty": ["Section 36(1) of LM Act 2009: Fine up to Rs. 25,000 for 1st offence"],
        "compounding": ["Compoundable"],
        "authority": ["Legal Metrology Officer"],
        "source_reference": "PCR 2011, Rule 4"
    },
    {
        "rule_id": "PCR_RULE_5",
        "jurisdiction": "CENTRAL",
        "legal_source": "Legal Metrology (Packaged Commodities) Rules, 2011",
        "section": None,
        "rule": "5",
        "sub_rule": "1-2",
        "clause": None,
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["specified_commodities", "standard_packages"],
        "conditions": ["commodities_listed_in_second_schedule"],
        "requirements": ["Commodities specified in Second Schedule must be packed in prescribed standard quantities (e.g. tea, biscuit, milk, oil)"],
        "exceptions": ["commodities_exempted_by_amendment_2021"],
        "exemptions": ["non_standard_packages_with_clear_unit_price_declaration"],
        "violation": ["Packing commodities in non-standard sizes prohibited in Second Schedule"],
        "evidence_required": ["Package weight verification report"],
        "penalty": ["Fine up to Rs. 25,000 under Section 36(1)"],
        "compounding": ["Compoundable"],
        "authority": ["Legal Metrology Officer"],
        "source_reference": "PCR 2011, Rule 5"
    },
    {
        "rule_id": "PCR_RULE_6",
        "jurisdiction": "CENTRAL",
        "legal_source": "Legal Metrology (Packaged Commodities) Rules, 2011",
        "section": None,
        "rule": "6",
        "sub_rule": "1",
        "clause": "a-g",
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["packaged_commodities", "retail_packages", "imported_goods"],
        "conditions": ["sold_in_pre_packaged_form"],
        "requirements": [
            "Name and address of the manufacturer/packer/importer",
            "Common or generic name of the commodity",
            "Net quantity in standard unit of weight/measure/number",
            "Month and year of manufacture/packing/import",
            "Maximum Retail Price (MRP) inclusive of all taxes",
            "Unit sale price (w.e.f. 2022 amendment for packages >1kg/1L)",
            "Consumer care details (name, address, telephone, email)"
        ],
        "exceptions": ["small_packages_under_10g_or_10ml"],
        "exemptions": ["wholesale_packages", "raw_materials_for_industrial_consumers"],
        "violation": ["Missing mandatory declaration", "Smudged/overwritten price tag", "Non-standard unit declaration", "Dual MRP"],
        "evidence_required": ["Seized/purchased retail package photograph", "Purchase invoice", "Verification report by LMO"],
        "penalty": ["Section 36(1) of Legal Metrology Act, 2009: Fine up to Rs. 25,000 for 1st offence, up to Rs. 50,000 for 2nd, up to Rs. 1,00,000 or imprisonment up to 1 year for subsequent offences"],
        "compounding": ["Compoundable by Controller/Authorized Legal Metrology Officer"],
        "authority": ["Director Legal Metrology (Central)", "Controller of Legal Metrology (Maharashtra)", "Legal Metrology Officer / Inspector"],
        "source_reference": "Legal Metrology (Packaged Commodities) Rules, 2011, Rule 6(1)"
    },
    {
        "rule_id": "PCR_RULE_7",
        "jurisdiction": "CENTRAL",
        "legal_source": "Legal Metrology (Packaged Commodities) Rules, 2011",
        "section": None,
        "rule": "7",
        "sub_rule": "1-3",
        "clause": None,
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["principal_display_panel", "font_height"],
        "conditions": ["package_surface_area"],
        "requirements": ["Declarations must appear on the Principal Display Panel; minimum font height specified according to net quantity area"],
        "exceptions": [],
        "exemptions": [],
        "violation": ["Font size smaller than statutory minimum height specified in Rule 7 table"],
        "evidence_required": ["Vernier caliper measurement of font height on PDP"],
        "penalty": ["Section 36(1) of LM Act 2009"],
        "compounding": ["Compoundable"],
        "authority": ["Legal Metrology Officer"],
        "source_reference": "PCR 2011, Rule 7"
    },
    {
        "rule_id": "PCR_RULE_8",
        "jurisdiction": "CENTRAL",
        "legal_source": "Legal Metrology (Packaged Commodities) Rules, 2011",
        "section": None,
        "rule": "8",
        "sub_rule": "1-2",
        "clause": None,
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["label_background", "contrast"],
        "conditions": ["visibility_and_legibility"],
        "requirements": ["Declarations must be conspicuous, legible, prominent, and in contrasting color to the background"],
        "exceptions": [],
        "exemptions": [],
        "violation": ["Transparent text on transparent package or low-contrast illegible text"],
        "evidence_required": ["High-resolution package photograph"],
        "penalty": ["Section 36(1) of LM Act 2009"],
        "compounding": ["Compoundable"],
        "authority": ["Legal Metrology Officer"],
        "source_reference": "PCR 2011, Rule 8"
    },
    {
        "rule_id": "PCR_RULE_18",
        "jurisdiction": "CENTRAL",
        "legal_source": "Legal Metrology (Packaged Commodities) Rules, 2011",
        "section": None,
        "rule": "18",
        "sub_rule": "1-5",
        "clause": None,
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["retail_sale", "mrp_compliance"],
        "conditions": ["retail_transactions"],
        "requirements": [
            "No retail dealer or trader shall sell any pre-packaged commodity at a price exceeding the Maximum Retail Price (MRP)",
            "Dual MRP on identical pre-packaged commodities is strictly prohibited",
            "Price tag stickers smudging original MRP are prohibited"
        ],
        "exceptions": [],
        "exemptions": [],
        "violation": ["Overcharging above printed MRP", "Dual MRP printing for different locations/malls"],
        "evidence_required": ["Purchase bill showing price higher than MRP printed on package", "Physical package sample"],
        "penalty": ["Section 36(2) of LM Act 2009: Fine up to Rs. 2,000 for retailer"],
        "compounding": ["Compoundable under Section 48"],
        "authority": ["Legal Metrology Officer / Controller"],
        "source_reference": "PCR 2011, Rule 18"
    },
    {
        "rule_id": "PCR_RULE_26",
        "jurisdiction": "CENTRAL",
        "legal_source": "Legal Metrology (Packaged Commodities) Rules, 2011",
        "section": None,
        "rule": "26",
        "sub_rule": "1-3",
        "clause": "a-d",
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["exemptions", "small_packages", "fast_food", "agricultural_produce"],
        "conditions": ["net_quantity_<=_10g_or_10ml", "wholesale_trade"],
        "requirements": [
            "Packages containing net quantity <= 10g or 10ml exempt from detailed individual package declarations if outer multipack declares details",
            "Wholesale packages exempt from retail MRP declarations",
            "Unpackaged fast food for immediate hotel consumption exempt"
        ],
        "exceptions": [],
        "exemptions": ["small_packages", "wholesale_packages", "immediate_consumption_food"],
        "violation": ["Attempting to penalize exempt small packages under Rule 26"],
        "evidence_required": ["Weight verification proving <= 10g/10ml net content"],
        "penalty": ["N/A - Statutory Exemption"],
        "compounding": ["N/A"],
        "authority": ["Legal Metrology Officer"],
        "source_reference": "PCR 2011, Rule 26"
    },
    {
        "rule_id": "PCR_RULE_27",
        "jurisdiction": "CENTRAL",
        "legal_source": "Legal Metrology (Packaged Commodities) Rules, 2011",
        "section": None,
        "rule": "27",
        "sub_rule": "1-4",
        "clause": None,
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["manufacturers", "packers", "importers"],
        "conditions": ["commencement_of_pre_packaging_or_import"],
        "requirements": [
            "Every manufacturer, packer, or importer of pre-packaged commodities must register their name and premises address with the Director or Controller within 90 days of commencement",
            "Application in Form I with prescribed fee"
        ],
        "exceptions": [],
        "exemptions": [],
        "violation": ["Operating pre-packaging or import business without mandatory Registration Certificate"],
        "evidence_required": ["Inspection memo", "Failure to produce Registration Certificate"],
        "penalty": ["Fine up to Rs. 4,000 for non-registration"],
        "compounding": ["Compoundable"],
        "authority": ["Director of Legal Metrology (Central)", "Controller of Legal Metrology (State)"],
        "source_reference": "PCR 2011, Rule 27"
    },

    # --- MAHARASHTRA LEGAL METROLOGY (ENFORCEMENT) RULES, 2011 ---
    {
        "rule_id": "MAHA_ENF_RULE_4",
        "jurisdiction": "MAHARASHTRA",
        "legal_source": "Maharashtra Legal Metrology (Enforcement) Rules, 2011",
        "section": None,
        "rule": "4",
        "sub_rule": "1-3",
        "clause": None,
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["inspection", "weights_and_measures", "commercial_premises"],
        "conditions": ["inspection_by_authorized_LMO"],
        "requirements": [
            "Legal Metrology Officer (LMO) in Maharashtra has power to inspect any commercial premises, test weights, measures, weighing instruments, and inspect pre-packaged goods"
        ],
        "exceptions": [],
        "exemptions": [],
        "violation": ["Obstructing Legal Metrology Officer in discharge of duties under Section 15"],
        "evidence_required": ["Panchnama", "LMO inspection logbook entry"],
        "penalty": ["Section 42 of LM Act 2009: Fine up to Rs. 10,000 or imprisonment"],
        "compounding": ["Non-compoundable obstruction"],
        "authority": ["Controller of Legal Metrology Maharashtra", "Legal Metrology Officer"],
        "source_reference": "Maharashtra Enforcement Rules 2011, Rule 4"
    },
    {
        "rule_id": "MAHA_ENF_RULE_6",
        "jurisdiction": "MAHARASHTRA",
        "legal_source": "Maharashtra Legal Metrology (Enforcement) Rules, 2011",
        "section": None,
        "rule": "6",
        "sub_rule": "1-4",
        "clause": None,
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["manufacturer_licence", "weights_and_measures"],
        "conditions": ["manufacturing_weight_or_measure_in_maharashtra"],
        "requirements": ["Obtain Manufacturer License in Form LM-1 from Controller of Legal Metrology Maharashtra"],
        "exceptions": [],
        "exemptions": [],
        "violation": ["Manufacturing commercial weights/scales without state license"],
        "evidence_required": ["Seizure memo of unlicensed factory premise"],
        "penalty": ["Section 23 of LM Act 2009: Fine up to Rs. 20,000, imprisonment up to 1 year for repeat"],
        "compounding": ["Compoundable by Controller"],
        "authority": ["Controller of Legal Metrology Maharashtra"],
        "source_reference": "Maharashtra Enforcement Rules 2011, Rule 6"
    },
    {
        "rule_id": "MAHA_ENF_RULE_14",
        "jurisdiction": "MAHARASHTRA",
        "legal_source": "Maharashtra Legal Metrology (Enforcement) Rules, 2011 Rule 14",
        "section": None,
        "rule": "14",
        "sub_rule": "1",
        "clause": None,
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["weights_and_measures", "commercial_traders", "repairers", "manufacturers"],
        "conditions": ["use_of_weight_or_measure_in_transaction"],
        "requirements": [
            "Periodical verification and stamping by Legal Metrology Officer (Every 12 months for commercial weights/scales, 24 months for storage tanks)",
            "Display of Verification Certificate at place of business"
        ],
        "exceptions": [],
        "exemptions": ["internal_industrial_testing_not_used_for_commercial_transaction"],
        "violation": ["Use of unverified weight or measure", "Expired verification stamp", "Missing Verification Certificate display"],
        "evidence_required": ["Inspection memo", "Seizure list of unverified scale", "Photograph of scale without valid seal"],
        "penalty": ["Section 24 of Legal Metrology Act, 2009: Fine up to Rs. 10,000, imprisonment up to 1 year for repeat offence"],
        "compounding": ["Compoundable under Section 48 of Legal Metrology Act, 2009"],
        "authority": ["Controller of Legal Metrology Maharashtra", "Assistant Controller", "Legal Metrology Officer"],
        "source_reference": "Maharashtra Legal Metrology (Enforcement) Rules, 2011, Rule 14"
    },
    {
        "rule_id": "MAHA_ENF_RULE_15",
        "jurisdiction": "MAHARASHTRA",
        "legal_source": "Maharashtra Legal Metrology (Enforcement) Rules, 2011",
        "section": None,
        "rule": "15",
        "sub_rule": "1-3",
        "clause": None,
        "effective_from": "2011-04-01",
        "effective_to": None,
        "applicability": ["compounding", "maharashtra_procedure"],
        "conditions": ["first_or_second_offence"],
        "requirements": ["Application for compounding in Form C to Controller / Deputy Controller Maharashtra within response window"],
        "exceptions": ["repeat_offence_within_3_years"],
        "exemptions": [],
        "violation": ["Filing compounding application for non-compoundable repeat offence"],
        "evidence_required": ["Form C application", "Compounding fee treasury receipt"],
        "penalty": ["Compounding fee as determined by Controller under Schedule V"],
        "compounding": ["Compoundable"],
        "authority": ["Controller of Legal Metrology Maharashtra"],
        "source_reference": "Maharashtra Enforcement Rules 2011, Rule 15"
    }
]

def seed_structured_rules(db: Session):
    for rdata in SEED_RULES:
        rule = RuleBase(**rdata)
        db.merge(rule)
    db.commit()
