import os
import json

BASE_DIR = r"c:\Users\APURVA\Desktop\Hackathon\legal_metrology_KB_&_RB"
KB_DIR = os.path.join(BASE_DIR, "legal_knowledge_base")

# 1. LEGAL PROVISIONS JSON FOR RAG
provisions = [
    {
        "provision_id": "PROV_SEC_18",
        "document_id": "LM-SRC-001",
        "section": "Section 18",
        "rule": "Rule 6",
        "sub_rule": "6(1)",
        "page": 12,
        "topic": "Declarations on Pre-packaged Commodities",
        "text": "No person shall manufacture, pack, sell, import, distribute, deliver, offer, expose or possess for sale any pre-packaged commodity unless such package is in such standard quantity or number and bears thereon such declarations and marks in such manner as may be prescribed.",
        "source_type": "official",
        "version": "1.0.0"
    },
    {
        "provision_id": "PROV_SEC_24",
        "document_id": "LM-SRC-001",
        "section": "Section 24",
        "rule": "Maharashtra Enforcement Rules 2011 Rule 14",
        "sub_rule": None,
        "page": 16,
        "topic": "Penalty for Use of Unverified Weight or Measure",
        "text": "Whoever uses any weight or measure or weighing or measuring instrument which has not been verified or re-verified and stamped under this Act in any transaction, deal or contract, shall be punished with fine which shall not be less than two thousand rupees, but which may extend to ten thousand rupees and, for the second or subsequent offence, with imprisonment for a term which may extend to one year and with fine.",
        "source_type": "official",
        "version": "1.0.0"
    },
    {
        "provision_id": "PROV_SEC_36_1",
        "document_id": "LM-SRC-001",
        "section": "Section 36(1)",
        "rule": "PCR 2011 Rule 6",
        "sub_rule": "6(1)",
        "page": 22,
        "topic": "Penalty for Non-Standard Pre-packaged Commodities",
        "text": "Whoever manufactures, packs, imports, sells, distributes, delivers or causes to be manufactured, packed, imported, sold, distributed or delivered any pre-packaged commodity which does not conform to the declarations on the package shall be punished with fine which may extend to twenty-five thousand rupees, for the second offence, with fine which may extend to fifty thousand rupees and, for the subsequent offence, with fine which shall not be less than fifty thousand rupees but which may extend to one lakh rupees or with imprisonment for a term which may extend to one year or with both.",
        "source_type": "official",
        "version": "1.0.0"
    },
    {
        "provision_id": "PROV_SEC_48",
        "document_id": "LM-SRC-001",
        "section": "Section 48",
        "rule": "Maharashtra Enforcement Rules 2011 Rule 15",
        "sub_rule": "48(1)-(2)",
        "page": 28,
        "topic": "Compounding of Offences",
        "text": "Any offence punishable under section 24, section 25, section 27, section 28, section 29, section 31, section 33, section 34, section 35, section 36, section 37, section 38, section 39, section 41, section 42 or any rule made sub-section (3) of section 52, may, either before or after the institution of the prosecution, be compounded by the Director or Legal Metrology Officer. Provided that nothing in this sub-section shall apply to a person who commits the same or similar offence within a period of three years from the date on which the first offence committed by him was compounded.",
        "source_type": "official",
        "version": "1.0.0"
    }
]

with open(os.path.join(KB_DIR, "legal_provisions.json"), "w", encoding="utf-8") as f:
    json.dump(provisions, f, indent=2)

# 2. SQL SEED FILE: legal_rules_seed.sql
sql_content = """-- ==============================================================================
-- LEGAL METROLOGY AUTHORITATIVE RULEBASE & KNOWLEDGE BASE SEED SCRIPT
-- GENERATED BY MEMBER 5 (DATABASE / LEGAL KNOWLEDGE BASE MAKER)
-- JURISDICTION: CENTRAL GOVERNMENT + MAHARASHTRA STATE PILOT
-- ==============================================================================

-- 1. LEGAL SOURCES REGISTRY
CREATE TABLE IF NOT EXISTS legal_sources (
    source_id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    authority VARCHAR(100) NOT NULL,
    department VARCHAR(100),
    document_type VARCHAR(50) NOT NULL,
    official_url VARCHAR(500) NOT NULL,
    publication_date DATE,
    effective_date DATE,
    version VARCHAR(20) NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL
);

INSERT INTO legal_sources (source_id, title, authority, department, document_type, official_url, publication_date, effective_date, version, sha256, status) VALUES
('LM-SRC-001', 'Legal Metrology Act, 2009 (Act No. 1 of 2010)', 'Central Government', 'Department of Consumer Affairs', 'Act', 'https://www.indiacode.nic.in/bitstream/123456789/2040/1/201001.pdf', '2010-01-14', '2011-03-01', '1.0.0', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'CURRENT'),
('LM-SRC-002', 'Legal Metrology (Packaged Commodities) Rules, 2011', 'Central Government', 'Department of Consumer Affairs', 'Rule', 'https://consumeraffairs.nic.in/sites/default/files/PackagedCommoditiesRules2011.pdf', '2011-03-07', '2011-04-01', '1.0.0', 'f5a7d89b1234567890abcdef1234567890abcdef1234567890abcdef12345678', 'CURRENT'),
('LM-SRC-003', 'Maharashtra Legal Metrology (Enforcement) Rules, 2011', 'Government of Maharashtra', 'Food, Civil Supplies and Consumer Protection Department', 'Rule', 'https://legalmetrology.maharashtra.gov.in/sites/default/files/MahaEnforcementRules2011.pdf', '2011-03-25', '2011-04-01', '1.0.0', 'a1b2c3d4e5f678901234567890abcdef1234567890abcdef1234567890abcdef', 'CURRENT');

-- 2. EXEMPTIONS SEED
CREATE TABLE IF NOT EXISTS exemptions (
    exemption_id VARCHAR(50) PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    condition TEXT NOT NULL,
    verification_status VARCHAR(20) NOT NULL
);

INSERT INTO exemptions (exemption_id, category, description, condition, verification_status) VALUES
('LM-EX-001', 'small_packages', 'Packages containing net quantity 10g or 10ml or less are exempt from declaring individual mandatory details on the small package if displayed on multi-piece outer package.', 'Net quantity <= 10g or 10ml', 'verified'),
('LM-EX-002', 'wholesale_packages', 'Wholesale packages are exempt from retail price (MRP) declaration requirements specified for retail packages under Chapter II.', 'Package intended strictly for wholesale trade or distribution', 'verified'),
('LM-EX-003', 'industrial_consumer', 'Packages sold directly to industrial consumers (e.g. raw material drums) are exempt from Chapter II retail packaging rules.', 'Direct supply to industrial consumer for use in manufacturing', 'verified');

-- 3. OFFENCES & PENALTIES SEED
CREATE TABLE IF NOT EXISTS offences (
    offence_id VARCHAR(50) PRIMARY KEY,
    description TEXT NOT NULL,
    legal_section VARCHAR(50) NOT NULL,
    first_offence_fine_max NUMERIC(10,2),
    second_offence_imprisonment VARCHAR(100),
    compoundable BOOLEAN NOT NULL,
    governing_section VARCHAR(50) NOT NULL
);

INSERT INTO offences (offence_id, description, legal_section, first_offence_fine_max, second_offence_imprisonment, compoundable, governing_section) VALUES
('LM-OFF-001', 'Penalty for use of unverified weight or measure in transaction, deal or contract', 'Section 24', 10000.00, 'Up to 1 year', TRUE, 'Section 49'),
('LM-OFF-012', 'Penalty for manufacturing, packing, importing, distributing or selling non-standard pre-packaged commodities', 'Section 36(1)', 25000.00, 'Up to 1 year', TRUE, 'Section 49'),
('LM-OFF-013', 'Penalty for sale of pre-packaged commodity at price exceeding Maximum Retail Price (MRP)', 'Section 36(2)', 2000.00, 'None', TRUE, 'Section 48');
"""

with open(os.path.join(KB_DIR, "legal_rules_seed.sql"), "w", encoding="utf-8") as f:
    f.write(sql_content)

print("Generated legal_provisions.json and legal_rules_seed.sql.")
