-- ==============================================================================
-- LEGAL METROLOGY AUTHORITATIVE RULEBASE & KNOWLEDGE BASE SEED SCRIPT
-- GENERATED BY MEMBER 5 (DATABASE / LEGAL KNOWLEDGE BASE MAKER)
-- JURISDICTION: CENTRAL GOVERNMENT + MAHARASHTRA STATE PILOT
-- ==============================================================================

-- 1. LEGAL SOURCES REGISTRY
CREATE TABLE IF NOT EXISTS legal_sources (
    source_id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    authority VARCHAR(100) NOT NULL,
    department VARCHAR(100),
    document_type VARCHAR(50) NOT NULL,
    official_url VARCHAR(500) NOT NULL,
    publication_date DATE,
    effective_date DATE,
    version VARCHAR(20) NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL
);

INSERT INTO legal_sources (source_id, title, authority, department, document_type, official_url, publication_date, effective_date, version, sha256, status) VALUES
('LM-SRC-001', 'Legal Metrology Act, 2009 (Act No. 1 of 2010)', 'Central Government', 'Department of Consumer Affairs', 'Act', 'https://www.indiacode.nic.in/bitstream/123456789/2040/1/201001.pdf', '2010-01-14', '2011-03-01', '1.0.0', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'CURRENT'),
('LM-SRC-002', 'Legal Metrology (Packaged Commodities) Rules, 2011', 'Central Government', 'Department of Consumer Affairs', 'Rule', 'https://consumeraffairs.nic.in/sites/default/files/PackagedCommoditiesRules2011.pdf', '2011-03-07', '2011-04-01', '1.0.0', 'f5a7d89b1234567890abcdef1234567890abcdef1234567890abcdef12345678', 'CURRENT'),
('LM-SRC-003', 'Maharashtra Legal Metrology (Enforcement) Rules, 2011', 'Government of Maharashtra', 'Food, Civil Supplies and Consumer Protection Department', 'Rule', 'https://legalmetrology.maharashtra.gov.in/sites/default/files/MahaEnforcementRules2011.pdf', '2011-03-25', '2011-04-01', '1.0.0', 'a1b2c3d4e5f678901234567890abcdef1234567890abcdef1234567890abcdef', 'CURRENT');

-- 2. EXEMPTIONS SEED
CREATE TABLE IF NOT EXISTS exemptions (
    exemption_id VARCHAR(50) PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    condition TEXT NOT NULL,
    verification_status VARCHAR(20) NOT NULL
);

INSERT INTO exemptions (exemption_id, category, description, condition, verification_status) VALUES
('LM-EX-001', 'small_packages', 'Packages containing net quantity 10g or 10ml or less are exempt from declaring individual mandatory details on the small package if displayed on multi-piece outer package.', 'Net quantity <= 10g or 10ml', 'verified'),
('LM-EX-002', 'wholesale_packages', 'Wholesale packages are exempt from retail price (MRP) declaration requirements specified for retail packages under Chapter II.', 'Package intended strictly for wholesale trade or distribution', 'verified'),
('LM-EX-003', 'industrial_consumer', 'Packages sold directly to industrial consumers (e.g. raw material drums) are exempt from Chapter II retail packaging rules.', 'Direct supply to industrial consumer for use in manufacturing', 'verified');

-- 3. OFFENCES & PENALTIES SEED
CREATE TABLE IF NOT EXISTS offences (
    offence_id VARCHAR(50) PRIMARY KEY,
    description TEXT NOT NULL,
    legal_section VARCHAR(50) NOT NULL,
    first_offence_fine_max NUMERIC(10,2),
    second_offence_imprisonment VARCHAR(100),
    compoundable BOOLEAN NOT NULL,
    governing_section VARCHAR(50) NOT NULL
);

INSERT INTO offences (offence_id, description, legal_section, first_offence_fine_max, second_offence_imprisonment, compoundable, governing_section) VALUES
('LM-OFF-001', 'Penalty for use of unverified weight or measure in transaction, deal or contract', 'Section 24', 10000.00, 'Up to 1 year', TRUE, 'Section 49'),
('LM-OFF-012', 'Penalty for manufacturing, packing, importing, distributing or selling non-standard pre-packaged commodities', 'Section 36(1)', 25000.00, 'Up to 1 year', TRUE, 'Section 49'),
('LM-OFF-013', 'Penalty for sale of pre-packaged commodity at price exceeding Maximum Retail Price (MRP)', 'Section 36(2)', 2000.00, 'None', TRUE, 'Section 48');
