import { Controller, Get, Param, Query } from '@nestjs/common';
import { ApiTags, ApiOperation } from '@nestjs/swagger';

const SEED_CASES = [
  {
    id: 'CASE-2026-001',
    productName: 'Mango Pickle 500g',
    status: 'underReview',
    openedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    violationSummary: 'Missing consumer care helpline details under Rule 6(1)(g)',
    role: 'INSPECTOR',
    counterpartyName: 'Maharashtrian Pickles & Spices SHG',
    currentStage: 'Draft Improvement Notice',
    deadline: new Date(Date.now() + 12 * 86400000).toISOString(),
    requiredAction: 'Issue formal notice',
    penaltyAmount: 5000,
    timeline: [
      {
        title: 'Inspection Completed',
        dateTime: new Date(Date.now() - 3 * 86400000).toISOString(),
        isDone: true,
        isCurrent: false,
        details: 'On-site verification completed by Inspector Rajesh Deshmukh',
        actor: 'Inspector',
      },
      {
        title: 'Notice Drafting',
        dateTime: new Date(Date.now() - 1 * 86400000).toISOString(),
        isDone: false,
        isCurrent: true,
        details: 'Improvement notice generated by AI rulebook pipeline',
        actor: 'System',
      },
    ],
  },
  {
    id: 'CASE-2026-002',
    productName: 'Fortified Sunflower Oil 1L',
    status: 'noticeIssued',
    openedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    violationSummary: 'Net quantity declaration font size below statutory minimum (Rule 7)',
    role: 'INSPECTOR',
    counterpartyName: 'Quality Packaged Commodities Pvt Ltd',
    currentStage: 'Awaiting Business Rectification',
    deadline: new Date(Date.now() + 8 * 86400000).toISOString(),
    requiredAction: 'Monitor compliance proof',
    penaltyAmount: 15000,
    timeline: [
      {
        title: 'Inspection Completed',
        dateTime: new Date(Date.now() - 7 * 86400000).toISOString(),
        isDone: true,
        isCurrent: false,
        details: 'Sample taken and digital panchanama recorded',
        actor: 'Inspector',
      },
      {
        title: 'Notice Issued',
        dateTime: new Date(Date.now() - 5 * 86400000).toISOString(),
        isDone: true,
        isCurrent: false,
        details: 'Improvement notice served via portal',
        actor: 'Inspector',
      },
      {
        title: 'Rectification Due',
        dateTime: new Date(Date.now() + 8 * 86400000).toISOString(),
        isDone: false,
        isCurrent: true,
        details: 'Business has 8 days remaining to submit corrected label',
        actor: 'Business',
      },
    ],
  },
];

@ApiTags('Legal Cases')
@Controller('api/v1/cases')
export class CasesController {
  @Get()
  @ApiOperation({ summary: 'List legal cases' })
  listCases(@Query('active') active?: string) {
    if (active === 'true') {
      return SEED_CASES.filter(c => c.status !== 'resolved' && c.status !== 'closed');
    }
    return SEED_CASES;
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get case by ID' })
  getCase(@Param('id') id: string) {
    const found = SEED_CASES.find(c => c.id === id);
    if (found) return found;
    return {
      id,
      productName: 'Sample Packaged Item',
      status: 'underReview',
      openedAt: new Date().toISOString(),
      violationSummary: 'Legal Metrology inquiry in progress',
      role: 'INSPECTOR',
      counterpartyName: 'Local Retailer',
      timeline: [],
    };
  }

  @Get(':id/timeline')
  @ApiOperation({ summary: 'Get timeline for case' })
  getTimeline(@Param('id') id: string) {
    const found = SEED_CASES.find(c => c.id === id);
    return found ? found.timeline : [];
  }
}
